### PR TITLE
Delegate `errors.haskell.org` domain to HF

### PR DESCRIPTION
**Pull request by tomjaguarpaw**

### CODE REVIEW

**Comment by romefeller** [comment]
Are we gonna vote on this proposal here or in the next meeting?

**Comment by tomjaguarpaw** [comment]
> how can we approach new efforts like `errors.haskell.org` without exacerbating this problem?

I hope this policy proposal is an example of how. If we had such policies for the other subdomains we would know who manages them and by what processes!

**Review by jaspervdj — CHANGES_REQUESTED** [review]
I love the idea of having an errors index, and in this case it is clearly documented who owns it.  However, I would like to have either an email address or a link to the HF contact page so people also know how to contact the owner.

**Comment by tomjaguarpaw** [comment]
> I would like to have either an email address or a link to the HF contact page

OK, added.

**Review by jaspervdj — APPROVED** [review]

**Review by TikhonJelvis — APPROVED** [review]
Sounds like a good plan to me

**Review by romefeller — APPROVED** [review]

**Review by rebeccaskinner — APPROVED** [review]
I think the errors domain is a great idea and I'm happy for the HF to take charge of that.

**Comment by tomjaguarpaw** [comment]
I approve this proposal (I'm not allowed to click Approve on GitHub since I authored the PR).  With 5 votes in favour and the threshold being 4 (out of 7) this policy is passed.

I suggest a representative of the HF contact [the Haskell admins](https://github.com/haskell-infra/haskell-admins) and ask for the change to be effected.

**Pull request merged**
